name: Clean Self Action Host
author: codetiger
description: Clean Self Action Host For New Host

runs:
  setps:
    - run: |
      ls /_work/${{ runner.name }}/ | grep -v '_actions' | grep -v '_PipelineMapping' | xargs -I {} rm -rf _work/${{ runner.name }}/{}
